# Generated by Django 5.2.11 on 2026-02-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
