# Generated by Django 5.2.11 on 2026-02-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_participant_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='payment_method',
            field=models.CharField(choices=[('MBWAY', 'MB Way'), ('LOCAL', 'Pagamento no local')], default='MBWAY', max_length=10),
        ),
    ]
