# Generated by Django 5.2.11 on 2026-03-03 21:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_participant_checked_in_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
