# Generated by Django 5.2.11 on 2026-03-03 21:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_registration_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
