# Generated by Django 5.2.11 on 2026-03-05 21:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_registration_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='ticket_code',
            field=models.CharField(blank=True, db_index=True, max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
    ]
