# Generated by Django 5.2.11 on 2026-03-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_participant_is_paid_participant_paid_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='ticket_code',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
    ]
