# Generated by Django 5.2.11 on 2026-03-13 13:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_participant_ticket_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='event_banner'),
        ),
    ]
