# Generated by Django 5.2.11 on 2026-03-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='ticket_code',
        ),
        migrations.AlterField(
            model_name='participant',
            name='full_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
