# Generated by Django 5.2.11 on 2026-03-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_participant_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='ticket_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
