# Generated by Django 5.2.11 on 2026-03-16 20:04

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryalbum',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='public_id',
        ),
        migrations.AlterField(
            model_name='galleryalbum',
            name='album_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data do culto/momento'),
        ),
        migrations.AlterField(
            model_name='galleryalbum',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='galleryalbum',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='galleryalbum',
            name='retention_days',
            field=models.PositiveIntegerField(choices=[(7, '7 dias'), (15, '15 dias'), (30, '30 dias')], default=30),
        ),
        migrations.AlterField(
            model_name='galleryalbum',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='gallery_image'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
