# Generated by Django 5.2.11 on 2026-03-16 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_galleryalbum_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryalbum',
            options={'ordering': ['-created_at'], 'verbose_name': 'Álbum da galeria', 'verbose_name_plural': 'Álbuns da galeria'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Imagem da galeria', 'verbose_name_plural': 'Imagens da galeria'},
        ),
        migrations.AlterField(
            model_name='galleryalbum',
            name='album_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data do culto / momento'),
        ),
        migrations.AlterField(
            model_name='galleryalbum',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_albums_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='galleryalbum',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expira em'),
        ),
        migrations.AlterField(
            model_name='galleryalbum',
            name='retention_days',
            field=models.PositiveIntegerField(choices=[(7, '7 dias'), (15, '15 dias'), (30, '30 dias')], default=30, verbose_name='Disponível durante'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expira em'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_images_uploaded', to=settings.AUTH_USER_MODEL),
        ),
    ]
