# Generated by Django 5.2.11 on 2026-03-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0003_alter_galleryalbum_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryalbum",
            name="retention_days",
            field=models.PositiveIntegerField(
                choices=[(0, "Sempre disponível"), (7, "7 dias"), (15, "15 dias"), (30, "30 dias")],
                default=30,
                verbose_name="Disponível durante",
            ),
        ),
    ]
